steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @testim/testim-cli
    testim \
    --token "Cmc0frSjzTLuisxBZpQY82qKdLuoNvxEUDJz2hipHgiSah1yke" \
    --project "QM2QXhQHvWoJolM9twdt" \
    --testId "DBKi3KLO5Mkr4OYm" \
    --grid "Testim-Grid" \
    --report-file testim-tests-report.xml
  displayName: 'npm install testim-cli and run tests'

- task: PublishTestResults@2
  displayName: 'publish testim test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testim-tests-report.xml'